export  const   VALIDAR_FORMULARIO  =   'VALIDAR_FORMULARIO';
export  const   VALIDAR_FORMULARIO_EXITO  =   'VALIDAR_FORMULARIO_EXITO';
export  const   VALIDAR_FORMULARIO_ERROR  =   'VALIDAR_FORMULARIO_ERROR';


export  const   AGREGAR_PRODUCTO  =   'AGREGAR_PRODUCTO';
export  const   AGREGAR_PRODUCTO_EXITO  =   'AGREGAR_PRODUCTO_EXITO';
export  const   AGREGAR_PRODUCTO_ERROR  =   'AGREGAR_PRODUCTO_ERROR';

export const    COMENZAR_DESCARGA_PRODUCTOS =   'COMENZAR_DESCARGA_PRODUCTOS';
export const    DESCARGA_PRODUCTOS_EXITO =   'DESCARGA_PRODUCTOS_EXITO';
export const    DESCARGA_PRODUCTOS_ERROR =   'DESCARGA_PRODUCTOS_ERROR';

export const    OBTENER_PRODUCTO_ELIMINAR =   'OBTENER_PRODUCTO_ELIMINAR';
export const    ELIMINAR_PRODUCTO_EXITO =   'ELIMINAR_PRODUCTO_EXITO';
export const    ELIMINAR_PRODUCTO_ERROR =   'ELIMINAR_PRODUCTO_ERROR';